# Generated by Django 2.0.1 on 2018-02-04 01:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
                model_name='article',
                name='slug',
        ),
    ]
