# Generated by Django 2.0.2 on 2018-03-04 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_remove_article_slug'),
    ]

    operations = [
        migrations.CreateModel(
                name='Comment',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('created', models.DateTimeField(auto_now_add=True)),
                    ('updated', models.DateTimeField(auto_now=True)),
                    ('content', models.TextField()),
                    ('is_show', models.BooleanField(default=True)),
                    ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments',
                                                  to='blog.Article')),
                    ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments',
                                                 to=settings.AUTH_USER_MODEL)),
                ],
                options={
                    'ordering': ('created',),
                },
        ),
    ]
