# Generated by Django 2.0.2 on 2018-03-04 12:57

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
                model_name='article',
                name='tags',
                field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.',
                                                      through='taggit.TaggedItem', to='taggit.Tag',
                                                      verbose_name='Tags'),
        ),
    ]
