# Generated by Django 2.0.3 on 2018-03-12 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='read_times',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
